# jwt 配置
jwt:
  signing-key: 'sky.he'

# zap logger 配置
zap:
  level: 'info'
  format: 'console'
  prefix: '[GINTEST->]'
  director: './log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true


# mysql 配置
mysql:
  path: '127.0.0.1:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'gin_test'
  username: 'root'
  password: '123456'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: true


# redis 配置
redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: '123456'