#https://docs.github.com/cn/actions/quickstart 官方文档
#https://www.ruanyifeng.com/blog/2019/09/getting-started-with-github-actions.html 阮一峰的action博客
name: reviewdog
on: [pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          golangci_lint_flags: "--enable-all --timeout=10m --exclude-use-default=false"